Cancelling.
niksy/throttle-debounce pull request #26
Opened 2018-10-26 00:36 UTC by whatknight

Addresses https://github.com/niksy/throttle-debounce/issues/6.

I started this a few days ago but I see there's already kind of an implementation in the time it took me to create this one. I figured I might as well open the PR for at least some discussion. 

I think this impl may be a little more thorough since after cancelling the the callback function will not be called again regardless of whether or not it was going to be executed in a timeout or synchronously. 

This also moves the documentation to the Usage section and provides an example.

2018-10-26 08:26 UTC, niksy commented
This looks great! Maybe you can combine `clearTimeout` calls into one method?

2018-11-28 16:02 UTC, whatknight commented
@niksy What do you think about merging this?

2018-11-30 10:35 UTC, CGNonofr commented
Are we waiting for something before merging and releasing this?

2018-12-16 01:36 UTC, JackRyder commented
Just found this task trying to figure out how to cancel a debounced function, is there an ETA on this being deployed? :+1:

2018-12-30 17:54 UTC, niksy requested changes

2018-12-30 17:54 UTC, niksy commented on README.md
> +Debounce and throttle can both be cancelling by calling the `cancel` function.
`cancelling` => `cancelled`

2018-12-30 17:54 UTC, niksy commented on README.md
> + var throttled = throttle(300, function () {
Could you please change `var` into `const` and function declaration into arrow function? I’m trying to promote modern-ish approach in docs :) You’re also welcome to change other references in README!

2018-12-30 17:55 UTC, niksy commented
@whatknight sorry for the wait! Can you please look at the requested changes?

2018-12-31 16:31 UTC, whatknight commented
@niksy thanks for the comments! i made the requested changes to the readme. let me know if there's anything else we need to do before we merge.

2019-01-02 09:22 UTC, niksy approved these changes

2019-01-03 18:01 UTC, niksy commented
@whatknight could you please rebase with `master` so we can merge your changes?

2019-01-12 14:32 UTC, whatknight commented
@niksy Just updated, sorry it took so long 😞 , been in a crunch.

2019-01-14 09:27 UTC, merged