Update to support UMD / browser
niksy/throttle-debounce pull request #41
Opened 2020-08-04 09:03 UTC by brekk

Hello,

I love the simplicity of this library; however when I try to use it via unpkg.com (https://unpkg.com/throttle-debounce@2.2.1/index.cjs.js) it ends up pointing at a commonjs implementation, which I cannot use in the browser.

In this PR I have updated the rollup configuration to support this.

While committing I ran into some issues w/r/t linting, but in files that I didn't touch — so I committed this as is, but please let me know if there's something additional I need to change.

Thanks,

Brekk

2020-08-05 14:17 UTC, brekk commented
@niksy At your earliest convenience.

2020-08-12 09:21 UTC, niksy requested changes

2020-08-12 09:21 UTC, niksy commented on .eslintrc
> +			"excludedFiles": "*.umd.js"
@brekk this is not needed

2020-08-12 09:21 UTC, niksy commented on .gitignore
> +*.swp
@brekk please remove this and add `index.umd.js` and `index.umd.js.map` to ignored files

2020-08-12 09:34 UTC, niksy requested changes

2020-08-12 09:34 UTC, niksy commented on index.umd.js
> +(function (global, factory) {
@brekk this file should be removed from Git since it’s now in `.gitignore`.

2020-08-12 09:34 UTC, niksy commented on index.umd.js.map
> +{"version":3,"file":"index.umd.js","sources":["throttle.js","debounce.js"],"sourcesContent":["/* eslint-disable no-undefined,no-param-reassign,no-shadow */\n\n/**\n * Throttle execution of a function
@brekk this file should be removed from Git since it’s now in `.gitignore`.

2020-08-12 09:36 UTC, brekk commented
@niksy 😅  whoops. Updated again.

2020-08-12 09:36 UTC, merged

2020-08-12 09:40 UTC, niksy commented
@brekk published as 2.3.0. Thanks for the PR!